fernando/apps/projects/urls.py
import re 
from django.urls import path
from  .views import  (project_list,project_detail,
					 project_create,
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c91cb4386d590368f205d60686c8801180347e3f

					 scope_detail,chapter_create,chapter_delete,
					 chapter_update,

					 scope_detail,chapter_create,chapter_delete,chapter_update
=======
					 scope_detail,chapter_create,chapter_delete,chapter_update,
                      meassurement_scope,meassurement_create,
                      meassurement_delete,entry_item_create
                      
                      
                     
>>>>>>> fernando



)

app_name = 'projects'
urlpatterns = [
   
    path('project_list', project_list, name='project_list'),
    path('project_detail/<id>/', project_detail, name='project_detail'),
    path('project_create/<id>/', project_create, name='project_create'),
    path('scope_detail/<id>', scope_detail, name='scope_detail'),
    path('chapter_create/<id>', chapter_create, name='chapter_create'),
    path('chapter_delete/<id>', chapter_delete, name='chapter_delete'),
    path('chapter_update/<id>', chapter_update, name='chapter_update'),
    path('meassurement_scope/<id>',  meassurement_scope, name= 'meassurement_scope'),
    path('meassurement_create/<id>',  meassurement_create, name= 'meassurement_create'),
    path('meassurement_delete/<id_meassurement>/<id_entry>',  meassurement_delete, name= 'meassurement_delete'),
    path('entry_item_create/<id_entry>',  entry_item_create, name= 'entry_item_create'),
   
    
    
]

fernando/fernando/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib .auth import urls as auth_urls
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('apps.users.urls')),
    path('', include('apps.profiles.urls')),
    path('', include('apps.invoices.urls')),
    path('', include('apps.projects.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
    

]



if settings.DEBUG :
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fernando/apps/offers/models.py
from django.db import models
from django.db.models.signals import post_save,post_delete,m2m_changed
from django.dispatch import receiver



class Price_Solicitude(models.Model):
	code             = models.CharField("Code", max_length=200, blank=True,null=True )
	date             = models.DateField('date',auto_now=False,blank=True,null=True)
	made_by          = models.ForeignKey('users.Profile_Employee', on_delete=models.CASCADE , blank=True,null=True,verbose_name='Made by' )
	items   	     = models.ManyToManyField('invoices.Item',blank=True,verbose_name="Items")
	provider         = models.ForeignKey('users.Profile_Provider' ,on_delete=models.CASCADE ,blank=True,null=True, verbose_name='Provider')
	project          = models.ForeignKey('projects.Project',on_delete=models.CASCADE , blank=True,null=True,verbose_name='Project' )
	

	def __str__(self):
		return "%s - %s" %(self.provider ,self.project.project_name)


class Solicitude_Entry(models.Model):

	item              = models.OneToOneField('projects.Entry_Item_Price' , on_delete=models.CASCADE, verbose_name='Item' )
	units             = models.CharField("units", max_length=200, blank=True,null=True ,default='units')
	quantity		  = models.DecimalField(blank=True,null=True, decimal_places=2,max_digits=10)
	price_solicitude  = models.ForeignKey(Price_Solicitude , on_delete=models.CASCADE, verbose_name='price_solicitude' )
	
	def save(self):
		self.quantity = self.item.quantity_needed
		super(Solicitude_Entry, self).save()

	class Meta:        
		verbose_name = "Solicitude of prices"
		verbose_name_plural = "Solicitude of prices"

fernando/apps/projects/models.py
from django.db import models
from django.db.models.signals import post_save,post_delete,m2m_changed
from django.dispatch import receiver
from apps.invoices.models import Buying_Entry

class Project(models.Model):
	"""docstring for invoice:"""

	ACCEPTED='ACT'
	WAITING = 'WFA'
	OVERULLED= 'REJ'
	STATE_TYPES = (
		(ACCEPTED, 'Accepted'),
        (WAITING, 'Waiting'),
        (OVERULLED, 'Overruled'),
               )
	project_name         = models.CharField(max_length=200, blank=True, null=True)
	project_number       = models.CharField(max_length=200, blank=True)
	date                 = models.DateField(null=True,blank=True)
	project_address      = models.CharField(max_length=200, blank=True,null=True)
	start_date           = models.DateField(null=True,blank=True)
	end_date             = models.DateField(null=True,blank=True)
	project_manager      = models.ManyToManyField('users.Profile_Employee', blank=True,verbose_name="Project manager",related_name='project_manager')
	site_manager         = models.ManyToManyField('users.Profile_Employee', blank=True ,verbose_name="site manager",related_name='site_manager')
	quantity_surveyor    = models.ManyToManyField('users.Profile_Employee', blank=True ,verbose_name="quantyty surveyor",related_name='quantity_surveyor')
	foreman              = models.ManyToManyField('users.Profile_Employee', blank=True ,verbose_name="Foreman",related_name='foreman')
	client               = models.ForeignKey('users.Profile_client',on_delete=models.CASCADE,null=True ,blank=True,verbose_name="client",related_name="client")
	state                = models.CharField(max_length=3, choices = STATE_TYPES,default=WAITING ,null=True)
	benefit_factor 	     = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20,default=1)
	custom_factor        = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20,default=1)
	indirect_cost_factor = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20,default=1)
	general_cost_factor  = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20,default=1)
	
	def __str__(self):
		return   self.project_name
	def save(self):
		if self.benefit_factor <=1:
			self.benefit_factor = 1
		if self.custom_factor <=0:
			self.custom_factor =1
		if self.indirect_cost_factor <=1:
			self.indirect_cost_factor=1
		if self.general_cost_factor<=1:
			self.general_cost_factor=1
		super(Project,self).save()

class Indirect_Cost(models.Model):
	project                = models.OneToOneField(Project, on_delete=models.CASCADE ,verbose_name="Project")
	date                   = models.DateField("Date", max_length=200, blank=True,null=True )
	valid_until            = models.DateField('Valid untill',blank=True,null=True)
	total_price            = models.DecimalField(blank=True,null=True,decimal_places=2,max_digits=10)

	def __str__(self):
		return self.project.project_name
	
class Indirect_Cost_Entry (models.Model):
	code                  = models.CharField("Code", max_length=200, blank=True,null=True )
	units     			  = models.CharField("Units", max_length=200, blank=True,null=True )
	entry_name            = models.CharField("Entry name ", max_length=200, blank=True,null=True )
	description           = models.TextField("Coments", max_length=400, blank=True,null=True,default='coments')
	items   	          = models.ManyToManyField('invoices.Item',blank=True,verbose_name="Items")
	chapter    	          = models.ForeignKey(Indirect_Cost,on_delete=models.CASCADE ,blank=True ,null=True, verbose_name='Chapter - Project')
	project    	          = models.ForeignKey(Project,on_delete=models.CASCADE ,blank=True ,null=True, verbose_name='Project')
	scope_quantity		  = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	planif_quantity	      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	target_quantity	      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	real_quantity	      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	scope_unt_price	      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	planif_unt_price      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	target_unt_price      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	real_unt_price        = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	scope_price		      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	planif_price          = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	target_price          = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	real_price            = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	
	

	def __str__(self):
		return "%s - %s" %(self.entry_name ,self.project.project_name)	


#presupuestos {{{ pendient  asociar precio a precio capitulos }}}
class Scope (models.Model):
	project                = models.OneToOneField(Project, on_delete=models.CASCADE ,verbose_name="Project")
	code                   = models.CharField("Code", max_length=200, blank=True,null=True )
	date                   = models.DateField("Date", max_length=200, blank=True,null=True )
	valid_until            = models.DateField('Valid untill',blank=True,null=True)
	total_price            = models.DecimalField(blank=True,null=True,decimal_places=2,max_digits=10)
	total_price_invoice    = models.DecimalField(blank=True,null=True,decimal_places=2,max_digits=10)
	total_price_planif     = models.DecimalField(blank=True,null=True,decimal_places=2,max_digits=10)
	total_price_target     = models.DecimalField(blank=True,null=True,decimal_places=2,max_digits=10)
	total_price_real       = models.DecimalField('Construction actual Price',blank=True,null=True,decimal_places=2,max_digits=10)

	
	

	def __str__(self):
		return self.project.project_name
	
	def save(self):

		#scope 
		try:
			self.chapter_prices_obj = self.chapter_set.all()
			quanties = self.chapter_prices_obj.values_list('total_price', flat=True)
			suma=0
			if quanties :
				for quantity in quanties:
					try:
						suma=suma+quantity
					except:
						quantity=0
			self.total_price = suma
		except:
			pass
		
		#invoice
		try:
			self.chapter_prices_invoice = self.chapter_set.all()
			quanties_invoice = self.chapter_prices_invoice.values_list('total_price_invoice', flat=True)
			suma=0
			if quanties_invoice :
				for quantity in quanties_invoice:
					try:
						suma=suma+quantity
					except:
						quantity=0
			self.total_price_invoice = suma
		except :
			self.total_price_invoice=0



		#target
		try:
			self.chapter_prices_target = self.chapter_set.all()
			quanties_target = self.chapter_prices_target.values_list('total_price_target', flat=True)
			suma=0
			if quanties_target :
				for quantity in quanties_target:
					try:
						suma=suma+quantity
					except:
						quantity=0
			self.total_price_target = suma
		except :
			self.total_price_target = 0


		try:
			self.chapter_prices_planif = self.chapter_set.all()
			quanties_planif = self.chapter_prices_planif.values_list('total_price_planif', flat=True)
			suma=0
			if quanties_planif :
				for quantity in quanties_planif:
					try:
						suma=suma+quantity
					except:
						suma=0
			self.total_price_planif = suma
		except :
			self.total_price_planif = 0




			

		#real
		try :
			self.chapter_prices_real = self.chapter_set.all()
			quanties_real = self.chapter_prices_obj.values_list('total_price_real', flat=True)
			suma=0
			if quanties_real :
				for quantity in quanties_real:
					try:
						suma=suma+quantity
					except:
						quantity=0
			self.total_price_real = suma
		except:
			pass

		super(Scope,self).save()

#signal 
@receiver(post_save, sender=Project)
def create_scope(sender, instance, created, **kwargs):
	if created:

		obj=Scope( project=instance )
		obj.code=instance.project_number
		obj.date=instance.date
		obj.save()
		obj.code=instance.project_number
		

	else:
		pass

@receiver(post_save, sender=Project)
def save_scope(sender, instance,**kwargs):
    obj = instance.scope
    obj.save()
    
#fases del proyecto   {{ pendiente actualizar metodo save() para todas las listas de precios}}
class Phase(models.Model):
	phase_code        = models.IntegerField( )
	phase_name        = models.CharField('Phase name ',max_length=200, blank=True,null=True)
	coments           = models.TextField("coments", max_length=400, blank=True,null=True,default='coments' )
	start_date        = models.DateField(blank=True, null=True)
	end_date          = models.DateField(blank=True, null=True)
	scope_price		  = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	invoice_price     = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	planif_price      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	target_price      = models.DecimalField(blank=True,decimal_places=2,null=True,max_digits=20)
	real_price        = models.DecimalField('Actual price',blank=True,decimal_places=2,null=True,max_digits=20)


	def __str__(self):
		return self.phase_name

	def save(self):
		#scope
		self.scope_meassurement = self.scope_meassurement_set.all()
		if self.scope_meassurement :
			total=0
			for obj in self.scope_meassurement:
				try:
					med=obj.total_meassurement*obj.entry.scope_unt_price
					total=total+med
				except:
					pass
			self.scope_price=total		
		else :
			self.scope_price=0
			#invoice
		self.invoice_meassurement = self.invoice_meassurement_set.all()
		if self.invoice_meassurement :
			total=0
			for obj in self.invoice_meassurement:
				try:
					med=obj.total_meassurement*obj.entry.invoice_unt_price
					total=total+med
				except:
					pass
			self.invoice_price=total		
		else :
			self.invoice_price=0
			#planificacion

fernando/apps/projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from fernando import settings



class Project_Creation_Form(ModelForm):


	
	class Meta:
		model = Project
		fields = '__all__'



class Entry_Creation_Form(ModelForm):

	class Meta:
		model = Entry
		fields = '__all__'


class Chapter_Creation_Form(ModelForm):

	class Meta:
		model = Chapter
		fields = ('code','units','chapter_name','quantity_scope','quantity_invoice','quantity_planif','quantity_target','quantity_real')

class Meassurement_Creation_Form(ModelForm):

	class Meta:
		model =  Scope_Meassurement
		exclude = ('entry ','total_meassurement', 'indirect_cost_entry',)


class Entry_Item_Price_Form (ModelForm) :

	model  =  Entry_Item_Price
	fields =  ('item', 'quantity_per_entry_unit_scope', 'item_price',)

fernando/apps/projects/templates/projects/meassurements/meassurement_list.html
{% extends 'users/base1.html' %}






{% block style %}
<style type="text/css">
  
  td, th {
    text-align: center;
  }


</style>
{% endblock %}


{% block content%}
<div style="border-bottom: solid 3px blue">
<h3><span style="float: right; font-size: 0.7em ">{{request.user.profile_employee.employee_name}}</span></h3>  
<h3> <span style="">Scope meassurements </span> <br> {{entry.entry_name}}  </h3>
</div>

<div style="margin-top: 10px">

  <div class='raw' >
  <div class="col-sm-5 " style="padding: 0px" >
      <button id="scope" style="margin-bottom: 15px" class="btn btn-primary" type="submit" class=""     >Scope</button>
      <button id='invoice' style="margin-bottom: 15px" class="btn btn-primary" type="submit" class=""   >Invoice</button>
      <button id='planif' style="margin-bottom: 15px" class="btn btn-primary" type="submit" class=""    >Planification</button>
      <button id="target" style="margin-bottom: 15px" class="btn btn-primary" type="submit" class=""    >Target</button>
      <button id="real" style="margin-bottom: 15px" class="btn btn-primary" type="submit" class=""      >Real</button>

  </div>

  <div id="meassurements-container">

        {% include 'projects/meassurements/partial_meassurements.html' %}

  </div>

   
 <button  

    type="button" 
    class="btn btn-primary btn-sm " 
    id="meassurements-load"   
    data-url=  "{% url 'projects:meassurement_create' id=entry.id %}"  
    style=" margin: auto; margin-top: 20px" > 


      <span style="margin-right: 7px" class="glyphicon glyphicon-plus" > 
        
      </span>Add new
  </button>



  <button type="button" 
      class="btn btn-danger btn-sm delete-meassurements-selected"   
      data-url=""     
      style=" margin: auto; margin-top: 20px" > 
      <span class="glyphicon glyphicon-trash" > 
      </span>Delete selected
  </button>


  <button   

    type="button" 
    class="btn btn-primary btn-sm meassurements-submit " 
    id=""   
    data-url=  ""  
    style=" margin: auto; margin-top: 20px; float: right;" > 


      <span style="margin-right: 7px" class="glyphicon glyphicon-plus" >
        
      </span>Submit Meassurements
  </button>



<div  style="margin-top: 10px">
      <button type="button" class="btn btn-warning btn-sm "   
      data-url=""   
      style=" margin: auto;" > 
      <span style="margin-right: 7px" class="glyphicon glyphicon-plus" ></span>Add to invoice
    </button>
    <button type="button" class="btn btn-warning btn-sm"   
      data-url=""   
      style=" margin: auto;" > 
      <span style="margin-right: 7px" class="glyphicon glyphicon-plus" ></span>Add to planif
    </button>
    <button type="button" class="btn btn-warning btn-sm "   
      data-url=""   
      style=" margin: auto;" > 
      <span style="margin-right: 7px" class="glyphicon glyphicon-plus" ></span>Add to target
    </button>
    <button type="button" class="btn btn-warning btn-sm"   
      data-url=""   
      style=" margin: auto;" > 
      <span style="margin-right: 7px" class="glyphicon glyphicon-plus" ></span>Add to real 
    </button>

</div>






{%endblock%}

fernando/apps/projects/templates/projects/meassurements/meassurement_list_real.html
<h1>Hi there</h1>

fernando/apps/projects/templates/projects/meassurements/meassurement_scope_form.html
{% load static %}
{% block style %}
<style type="text/css">
  input {
    border: none;
    width: 100%;
  }
  input #coments {
    
  }

</style>

{% endblock %}



<form style="margin-bottom: 20px ;margin: 0px" method="post"
   action=  "{% url 'projects:meassurement_create' id=entry.id %}"  
   class="js-meassurement-create-form">
  {% csrf_token %}

<table style="text-align: center; margin: 0px " border="0"  class="table table-bordered ">

    <tr id='{{entry.id}}'>
        <td id="coments" style="width: 40.5% "><input placeholder="coments" type="text" name="coments" maxlength="200" id="id_coments">  </td>
        <td><input placeholder="loc" type="text" name="location" maxlength="10" id="id_ud_type">  </td>



        <td><input placeholder="Units" type="text" name="ud_type" maxlength="200" id="id_ud_type">  </td>
        <td><input placeholder="Quantity" type="number" name="quantity" step="1" id="id_quantity"> </td>
        <td><input placeholder="Width" type="number" name="width" step="1" id="id_width">    </td>
        <td><input placeholder="high" type="number" name="high" step="1" id="id_high">     </td>
        <td><input placeholder="Wide" type="number" name="wide" step="" id="id_wide">     </td>
       
        <td>
          {{form.phase}}       
        </td>
    </tr>

</table>

</form>

fernando/apps/projects/templates/projects/meassurements/partial_meassurement_form.html
<form method="post" action="" 
class="js-meassurement-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm Meassurement deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete these meassurement? 
   </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Meassurements</button>
  </div>
</form>

fernando/apps/projects/templates/projects/meassurements/partial_meassurements.html
<form>
<table style="text-align: center;" width="100%" border="0"  class="table table-bordered ">

    <tr style="background:#B39609">
      <th style="width: 12%"></th>
      
      <th style="min-width: 270px">COMENTS</th>
      <th >UNITS</th>
      <th>QUANTITY  </th>
      <th>WIDTH</th>
      <th>HIGH</th>
      <th>WIDE</th>
      <th>TOTAL: {{entry.scope_quantity}}</th>
      <th>PHASE</th>

    </tr>

{%for obj in meassurement_list %}

  <tr style="" id="{{entry.id}}" >
    <td><input 
      type="checkbox" 
      name=" {{entry.entry_name}}"
      id="{{obj.id}}"
      data-url="{% url 'projects:meassurement_delete'  id_meassurement=obj.id  id_entry=entry.id %}" >


     <button 
      data-url="" 
      id=" {{obj.id}}" style="" class="btn btn-warning btn-xs js-update-meassurement" type="submit" class="">
      <span class="glyphicon glyphicon-pencil"></span> 
       </button> 

      <button 
      data-url="{% url 'projects:meassurement_delete'  id_meassurement=obj.id  id_entry=entry.id %}"  
      id=" {{obj.id}}"
      style=" margin-left: 7px" 
      class="btn btn-danger btn-xs meassurement-delete" 
      type="" >
      
      <span class="glyphicon glyphicon-trash"> </span> 
    </button>

    </td>
    <td>{{obj.coments}}</td>
    <td>{{obj.ud_type}} </td>
    <td>{{obj.quantity}} </td>
    <td>{{obj.width}}</td>
    <td>{{obj.high}}</td>
    <td>{{obj.wide}} </td>
    <td>{{obj.total_meassurement}} </td>
    <td>{{obj.phase}} </td>
  </tr>
{% empty %}
        <tr>
          <td colspan="9" class="text-center bg-warning">No Meassurements</td>
        </tr>
  
{%endfor%}

</table>

<form>