fernando/apps/projects/urls.py
import re 
from django.urls import path
from  .views import  (project_list,project_detail,
					 project_create,
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c91cb4386d590368f205d60686c8801180347e3f

					 scope_detail,chapter_create,chapter_delete,
					 chapter_update,

					 scope_detail,chapter_create,chapter_delete,chapter_update
=======
					 scope_detail,chapter_create,chapter_delete,chapter_update,
                      meassurement_scope,meassurement_create,
                      meassurement_delete,entry_item_create
                      
                      
                     
>>>>>>> fernando



)

app_name = 'projects'
urlpatterns = [
   
    path('project_list', project_list, name='project_list'),
    path('project_detail/<id>/', project_detail, name='project_detail'),
    path('project_create/<id>/', project_create, name='project_create'),
    path('scope_detail/<id>', scope_detail, name='scope_detail'),
    path('chapter_create/<id>', chapter_create, name='chapter_create'),
    path('chapter_delete/<id>', chapter_delete, name='chapter_delete'),
    path('chapter_update/<id>', chapter_update, name='chapter_update'),
    path('meassurement_scope/<id>',  meassurement_scope, name= 'meassurement_scope'),
    path('meassurement_create/<id>',  meassurement_create, name= 'meassurement_create'),
    path('meassurement_delete/<id_meassurement>/<id_entry>',  meassurement_delete, name= 'meassurement_delete'),
    path('entry_item_create/<id_entry>',  entry_item_create, name= 'entry_item_create'),
   
    
    
]

fernando/apps/users/urls.py
import re 
from django.urls import path
from django.contrib.auth import views as auth_views
from  .views import  (
	home , user_list, user_create,user_update,user_delete,user_filter_list,
	validate_username

		)
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
   
    path('', home, name='home'),
    path('user_list', user_list, name='user_list'),
    path('user_create', user_create, name='user_create'),
    path('user/<id>/update', user_update, name='user_update'),
    path('user/<id>/delete', user_delete, name='user_delete'),
    path('user_filter_list', user_filter_list, name='user_filter_list'),
    path('login/', auth_views.login,{'template_name':'users/login.html' }, name='login'),
    path('logout/', auth_views.logout,{'next_page': '/'}, name='logout'),
    path('ajax/validate_username/', validate_username, name='validate_username'),
    
]

fernando/fernando/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib .auth import urls as auth_urls
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('apps.users.urls')),
    path('', include('apps.profiles.urls')),
    path('', include('apps.invoices.urls')),
    path('', include('apps.projects.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
    

]



if settings.DEBUG :
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fernando/apps/projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from fernando import settings



class Project_Creation_Form(ModelForm):


	
	class Meta:
		model = Project
		fields = '__all__'



class Entry_Creation_Form(ModelForm):

	class Meta:
		model = Entry
		fields = '__all__'


class Chapter_Creation_Form(ModelForm):

	class Meta:
		model = Chapter
		fields = ('code','units','chapter_name','quantity_scope','quantity_invoice','quantity_planif','quantity_target','quantity_real')

class Meassurement_Creation_Form(ModelForm):

	class Meta:
		model =  Scope_Meassurement
		exclude = ('entry ','total_meassurement', 'indirect_cost_entry',)


class Entry_Item_Price_Form (ModelForm) :

	model  =  Entry_Item_Price
	fields =  ('item', 'quantity_per_entry_unit_scope', 'item_price',)

fernando/apps/projects/views.py
from django.shortcuts import render
from .models import *
from .forms import  Project_Creation_Form,Chapter_Creation_Form, Meassurement_Creation_Form
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from apps.users.decorators import superuser,is_client
from django.contrib.auth.decorators import login_required
from apps.users.models import User, Profile_Employee
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.http import JsonResponse

@superuser
def project_list(request, **kwargs):
	user    = Project.objects.all().order_by('-date')
	template = 'projects/project_list.html'
	query = request.GET.get('q', "")
	if query:
		user=user.filter(
        	Q(project_name__icontains=query)|
        	Q(client__icontains=query)|
        	q(project_manager__icontains=query)
            )
	paginator = Paginator(user, 10)
	page = request.GET.get('page', 1)
	try:
		users = paginator.page(page)
	except PageNotAnInteger:
		users = paginator.page(1)
	except EmptyPage:
		users = paginator.page(paginator.num_pages)
	return render(request, template, {'projects': users})


@superuser
def project_detail(request,**kwargs):
	template = 'projects/project_detail.html'
	obj = get_object_or_404(Project, id=kwargs['id'])
	context = {'obj':obj}
	return render( request, template, context)


def project_create(request, **kwargs):
	template= 'projects/project_create.html'

	obj = get_object_or_404(Project, id=kwargs['id'])
	if request.method == 'POST':
		form = Project_Creation_Form(request.POST, instance=obj )
		if form.is_valid():
			it=form.save(commit =False)

			project_manager     =form.cleaned_data['project_manager']
			
			site_manager        =form.cleaned_data['site_manager']
			quantity_surveyor   =form.cleaned_data['quantity_surveyor']
			foreman             =form.cleaned_data['foreman']
			client              = form.cleaned_data['client']
			it.save()
			fo =it.foreman.all()
			sm = it.site_manager.all()
			qs = it.quantity_surveyor.all()
			pm = it.project_manager.all()
			if site_manager:	
				for obj in site_manager:
					if obj in sm:
						pass
					else:
						it.site_manager.add(obj)
			elif  not site_manager:
				for obj in sm:
					it.site_manager.remove(obj)

			for obj in sm:
				if obj in site_manager:
					pass
				else:
					it.site_manager.remove(obj)
			else:
				pass
			

			if quantity_surveyor:	
				for obj in quantity_surveyor:
					if obj in qs :
						pass
					else:
						it.quantity_surveyor.add(obj)
			elif  not foreman:
				for obj in fo:
					it.foreman.remove(obj)

			for obj in qs:
				if obj in quantity_surveyor:
					pass
				else:
					it.quantity_surveyor.remove(obj)
			else:
				pass

			if foreman:	
				for obj in foreman:
					if obj in fo :
						pass
					else:
						it.foreman.add(obj)
			elif  not foreman:
				for obj in fo:
					it.foreman.remove(obj)

			for obj in fo:
				if obj in foreman:
					pass
				else:
					it.foreman.remove(obj)
			else:
				pass


			if project_manager:	
				for obj in project_manager:
					if obj in pm :
						pass
					else:
						it.project_manager.add(obj)
			elif  not project_manager:
				for obj in pm:
					it.project_manager.remove(obj)

			for obj in pm :
				if obj in project_manager:
					pass
				else:
					it.project_manager.remove(obj)
			else:
				pass	
		return redirect ('projects:project_create' ,id=kwargs['id'])
	else:
		
		form=Project_Creation_Form(instance=obj)
		context = {'form':form ,'obj':obj}

		return render(request, template, context)


@superuser
def scope_detail(request,**kwargs):

	template   = 'projects/scope.html'


	project     = get_object_or_404(Project, id=kwargs['id'])
	scope       = Scope.objects.get(project=project)
	chapters    = Chapter.objects.filter(scope=scope)
	user        = get_object_or_404(User , email=request.user.email)

	context={
				
				'project':project,
				'scope':scope,
				'chapters':chapters,
				'user':user
			
	}

	return render(request,template, context )

def save_chapter_form(request, form, template_name, id):
    data = dict()
   
    if request.method == 'POST':
        if form.is_valid():
          	form.save()
          	scope       = get_object_or_404(Scope , id=id)
          	chapters    = Chapter.objects,filter(scope=scope)
          	project     = scope.project
          	user        = get_object_or_404(User , email=request.user.email)
          	context={'project':project,'scope':scope,'chapters':chapters,'user':user}
          	data['form_is_valid'] = True
          	data['html_scope'] = render_to_string('projects/scope_partial.html', context)
        else:
            data['form_is_valid'] = False
    context = {'form': form , 'id':id}
    print(id)
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@superuser				
def chapter_create(request ,**kwargs):

	scope_id = kwargs['id']
	scope = get_object_or_404(Scope , id=scope_id)
	initial =scope

	id=kwargs['id']
	scope = get_object_or_404(Scope , id=id)
	

	print (scope)
	if request.method == 'POST':
		form = Chapter_Creation_Form(request.POST)
		
	else:
		form = Chapter_Creation_Form()
	return save_chapter_form(request, form, 'projects/chapters/partial_chapter_create.html',id)

@superuser
def chapter_update(request, id):

   


	data=dict()
	chapter = get_object_or_404(Chapter, id=id)
	scope       = Scope.objects.get(chapter=chapter)
	user        = get_object_or_404(User , email=request.user.email)
	project     = scope.project
	chapters    = Chapter.objects.filter(scope=scope)
	context={
        		'project':project,
				'scope':scope,
				'chapters':chapters,
				'user':user
				}
	if request.method == 'POST':
		form = Chapter_Creation_Form(request.POST, instance=chapter)
		if form.is_valid():
			chapter.save()
			data['form_is_valid'] = True  # This is just to play along with the existing code
			data['html_scope'] = render_to_string('projects/scope_partial.html', context)

		else:
			data['form_is_valid'] = False
	form = Chapter_Creation_Form(instance=chapter)
	data['html_form'] = render_to_string('projects/chapters/partial_chapter_update.html', {'form':form} , request=request)
	return JsonResponse(data)


@superuser
def chapter_delete(request, id):
    
    data = dict()
   
    chapter     = get_object_or_404(Chapter ,id=id)
    scope       = Scope.objects.get(chapter=chapter)
    user        = get_object_or_404(User , email=request.user.email)
    project     = scope.project
    chapters    = Chapter.objects.filter(scope=scope)
    context={
				'chapters':chapters,
				'project':project,
				'scope':scope,
				'user':user
			
	}
    if request.method == 'POST':
        chapter.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        data['action']='delete'
        data['html_scope'] = render_to_string('projects/scope_partial.html', context)
    else:
        context = {'chapter':chapter}
        data['html_form'] = render_to_string('projects/chapters/partial_chapter_delete.html', context, request=request,)
    return JsonResponse(data)

####MEASSUREMENTS
#####################################################


@superuser
def meassurement_scope(request , **kwargs):

	template = 'projects/meassurements/meassurement_list.html'
	id_entry =kwargs['id']
	entry = get_object_or_404(Entry, id=id_entry)
	meassurement_list =  Scope_Meassurement.objects.filter(entry=entry).order_by('id')
	context ={
			'entry':entry,
			"meassurement_list":meassurement_list
	}
	return render (request , template, context)


#crear mediciones ajax
@superuser			
def meassurement_create(request ,**kwargs):
	data=dict()
	id_entry =kwargs['id']
	entry       = get_object_or_404(Entry, id=id_entry)
	meassurements =Scope_Meassurement.objects.filter(entry=entry)
	context={
        		'entry':entry,
				'meassurement_list':meassurements
				}
	if request.method == 'POST':
		form = Meassurement_Creation_Form(request.POST)
		
		if form.is_valid():

			obj=form.save(commit=False)
			if obj.quantity == None and obj.coments == None:
				data['form_is_valid'] = True
				meassurement_list = Scope_Meassurement.objects.filter(entry=entry)
				data['html_meassurements'] = render_to_string('projects/meassurements/partial_meassurements.html',
																{'meassurement_list':meassurement_list,
																'entry':entry })
			else:
				obj.entry=entry
				obj.save()
				meassurement_list = Scope_Meassurement.objects.filter(entry=entry)

				data['form_is_valid'] = True  # This is just to play along with the existing code
				data['html_meassurements'] = render_to_string('projects/meassurements/partial_meassurements.html',
																{'meassurement_list':meassurement_list,
																'entry':entry })

		else:
			data['form_is_valid'] = False
	form = Meassurement_Creation_Form()
	data['html_form'] = render_to_string('projects/meassurements/meassurement_scope_form.html',
										 {'form':form ,'entry':entry} , 
										 request=request)
	return JsonResponse(data)

@superuser
def meassurement_delete(request ,**kwargs):

	data = dict()
	id_meassurement   = kwargs['id_meassurement']
	id_entry          = kwargs['id_entry']
	entry             = get_object_or_404(Entry, id=id_entry)
	meassurement      = get_object_or_404(Scope_Meassurement, id=id_meassurement)
	meassurements     = Scope_Meassurement.objects.filter(entry=entry)
	
	if request.method == 'GET':
		meassurement.delete()
		

		meassurement_list = Scope_Meassurement.objects.filter(entry=entry)
	
		data['html_meassurements'] = render_to_string('projects/meassurements/partial_meassurements.html',
														{'meassurement_list' : meassurement_list,
														'entry':entry },
														request=request)
	if  request.method == 'POST':
		meassurement.delete()
		meassurement_list = Scope_Meassurement.objects.filter(entry=entry)
	

fernando/apps/projects/templates/projects/partial_project_list.html
{% load static %}
{% for project in projects %}
 
        <tr>

           <td><a style="" href="{%url 'projects:project_create' id=project.id   %}" >{{ project.project_name }}</a></td>
           <td>{{ project.project_number }}</td>
           <td>{{ project.project_address}}</td>
           <td>{{ project.start_date}} </td>                                       
           <td> 
            {% for man in project.project_manager.all %}
            <p>{{ man }}</p>
            {% endfor %}

          </td>                                       
           <td>{{ project.client}}</td>
           <td>{{ project.state}}</td>
           <td>
      <button type="button"
              class="btn btn-warning btn-sm js-update-book"
              data-url="">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-book"
              data-url="">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </td>
    </tr>
      {% empty %}
        <tr>
          <td colspan="7" class="text-center bg-warning">No users</td>
        </tr>
      {% endfor %}
 

fernando/apps/projects/templates/projects/scope_partial.html
{%block style%}
<style type="text/css">
  
a {
  color: white;
}


</style>

{% endblock %}








<table style="text-align: center;" width="100%" border="0"  class="table table-bordered ">
  <tbody>
    <tr  style="background:#B39609" >
      
      <th scope="col"> 
       <span class="glyphicon glyphicon-cog"></span>
      </th>
      <th scope="col"                                                     >Code</th>
      <th scope="col"                                                     >Unit</th>
      <th style="min-width: 250px" scope="col"                            >{{scope.project.project_name}}</th>
      <th class="scope" scope="col"                                       >Quantity[scope]</th>
      <th style="display: none;"  class="invoice" scope="col"             >Quantity[Invoice]</th>
      <th style="display: none;"  class="planif" scope="col"              >Quantity[Planif.]</th>
      <th style="display: none;"  class="target" scope="col"              >Quantity[Target]</th>
      <th style="display: none;"  class="real" scope="col"                >quantity[Real]</th>
      <th                         class="scope " scope="col"><span        >Unitary Price</span><br><span></span> </th>
      <th style="display: none;"  class="invoice " scope="col"><span      >Unitary Price[Invoice]</span><br><span></span> </th>
      <th style="display: none;"  class="planif " scope="col"><span       >Unitary Price[Planif]</span><br><span></span> </th>
      <th style="display: none;"  class="target " scope="col"><span       >Unitary Price[Target]</span><br><span></span> </th>
      <th style="display: none;"  class="real " scope="col"><span         >Unitary Price[Real]</span><br><span></span> </th>
      <th                         class="scope " scope="col"><span        >Total Price</span><br><span>{{scope.total_price}}</span> </th>
      <th style="display: none;"  class="invoice" scope="col"><span       >Total Price[Invoice]</span><br><span>{{scope.total_price_invoice}}</span></th>
      <th style="display: none;"  class="planif" scope="col"><span        >Total Price[Planif]</span><br><span>{{scope.total_price_planif}}</span></th>
      <th style="display: none;"  class="target" scope="col"><span        >Total Price[Target]</span><br><span>{{scope.total_price_target}}</span></th>
      <th style="display: none;"  class="real " scope="col"><span         >Total Price[Real]</span><br><span>{{scope.total_price_real}}</span></th>
    </tr>

    {% for  chapter in chapters  %}


	    <tr  class='main' style="background:#AAC7A0">

<<<<<<< HEAD



    {% for  chapter in chapters  %}
	 <tr  class='main' style="background:#AAC7A0">

      <td style="width: 95px">                                                                                 
         
<<<<<<< HEAD
      <button data-url="{% url 'projects:chapter_update' id=chapter.id %}" id="" style="" class="btn btn-warning btn-xs js-update-chapter" type="submit" class=""><span class="glyphicon glyphicon-pencil"></span> </button> 


=======
      <button data-url="{% url 'projects:chapter_update' chapter.id %}" id="" style="" class="btn btn-warning btn-xs js-update-chapter" type="submit" class=""><span class="glyphicon glyphicon-pencil"></span> </button> 
>>>>>>> adec64c
      <button data-url="{% url 'projects:chapter_delete' chapter.id %}" style="" class="btn btn-danger btn-xs js-delete-chapter" type="submit" class=""><span class="glyphicon glyphicon-trash"></span> </button> 


<<<<<<< HEAD
=======
      <td style="width: 95px">                                                   
        <button 
      data-url="{% url 'projects:chapter_update' chapter.id %}" 
      id="" style="" class="btn btn-warning btn-xs js-update-chapter" type="submit" class="">
      <span class="glyphicon glyphicon-pencil"></span> 
       </button> 
        <button 
      data-url="{% url 'projects:chapter_delete' chapter.id %}" 
      style="" class="btn btn-danger btn-xs js-delete-chapter" type="submit" class="">
      <span class="glyphicon glyphicon-trash"></span> 
      </button> 
>>>>>>> fernando
=======
>>>>>>> c91cb4386d590368f205d60686c8801180347e3f
      </td>
      <td                                                                                 >{{chapter.code}}</td>
      <td                                                                                 >{{chapter.units}}</td>
      <td id="{{chapter.id}}" style="width: 100%; font-weight: bold; "  class='btn entry'>{{chapter.chapter_name|upper}}</td>
      <td style=""                class="scope          "       >{{chapter.quantity_scope}}</td>
      <td style="display: none;"  class="invoice       "        >{{chapter.quantity_invoice}}</td>
      <td style="display: none;"  class="planif         "       >{{chapter.quantity_planif}}</td>
      <td style="display: none;"  class="target          "      >{{chapter.quantity_target}}</td>
      <td style="display: none;"  class="real           "       >{{chapter.quantity_real}}</td>
      <th style=""  scope="col"   class="scope          "       >{{  chapter.price_unit_scope}}</th>
      <th style="display: none;"  class="invoice"scope="col"    >{{  chapter.price_unit_invoice}}</th>
      <th style="display: none;"  class="planif "scope="col"    >{{  chapter.price_unit_planif}}</th>
      <th style="display: none;"  class="target" scope="col"    >{{  chapter.price_unit_target}}</th>
      <th style="display: none;"  class="real  " scope="col"    >{{  chapter.price_unit_real}}</th>
      <td                         class=" scope price  "        >{{chapter.total_price}}</td>
      <td style="display: none;"  class="invoice       "        >{{chapter.total_price_invoice}}</td>
      <td style="display: none;"  class="planif        "        >{{chapter.total_price_planif}}</td>
      <td style="display: none;"  class="target        "        >{{chapter.total_price_target}}</td>
      <td style="display: none;"  {% if  chapter.total_price_target <  chapter.total_price_real %}  class="real perdidas "   {%  elif   chapter.total_price_real <  chapter.total_price_target %} class="real ganacias  " {%  else  %}  class= 'real'{% endif %} >{{chapter.total_price_real}}</td>

</tr>
  <tr class="{{chapter.id}} " style="display: none;">
    <td style="width: 95px">                                                                                 
      <button 
      id="" 
      style="" 
      class="btn btn-primary btn-xs" 
      type="submit" class="">
      <span class="glyphicon glyphicon-plus"></span>Entry 
    </button>     
    <td colspan="4" >   ENTRIES OF {{ chapter.chapter_name|upper}}</td>

  </tr>
     

      {% for  entry in chapter.entry_set.all  %}


  <tr class="{{chapter.id}} "  style="background: lightgrey; font-size: 1em ;display: none;" >
      <td style="width: 80px"> 
         
      <button 
      id="" 
      style="" 
      name="{{entry.entry_name}}"
      class="btn btn-warning btn-xs" 
      type="" class="">
      <span class="glyphicon glyphicon-pencil"></span> 
      </button> 
      <button id="" style="" class="btn btn-danger btn-xs" type="submit" class="">
      <span class="glyphicon glyphicon-trash"></span> 
     </button> 
      </td> 
               
      <td>                                                                             {{entry.code}}</td>
      <td>                                                                            {{entry.units}}</td>
      <td id='{{entry.id}}' style="width: 100% ;font-weight: bold;"  class='btn item' >{{entry.entry_name}}</td>
      <td class="scope">
        <button 
         data-url="{% url 'projects:meassurement_scope' entry.id %}"
         name="{{entry.entry_name}}"
        id=" meassurement_scope " 
        style=" float: left;" 
        class="btn btn-warning btn-xs  meassurement_scope" 
        type="submit" class=""    
       
        ><span class="glyphicon glyphicon-list"></span> 
        </button>                                                                                {{entry.scope_quantity}}</td>
      <td style="display: none;" class="invoice" ><button id="" style=" float: left;" class="btn btn-warning btn-xs" type="submit" class=""><span class="glyphicon glyphicon-list"></span> </button>        {{entry.invoice_quantity}}</td>


      <td style="display: none;" class="planif "                                      ><button id="" style=" float: left;" class="btn btn-warning btn-xs" type="submit" class=""><span class="glyphicon glyphicon-list"></span> </button> {{entry.planif_quantity}}</td>
      <td style="display: none;"  class="target"                                      ><button id="" style=" float: left;" class="btn btn-warning btn-xs" type="submit" class=""><span class="glyphicon glyphicon-list"></span> </button> {{entry.target_quantity}}</td>
      <td style="display: none;"  class="real"> 
         <button 
         data-url=""
         name="{{entry.entry_name}}"
        id=" meassurement_real " 
        style=" float: left;" 
        class="btn btn-warning btn-xs  meassurement_real " 
        type="submit"    
       
        ><span class="glyphicon glyphicon-list"></span> 
        </button>    
      {{entry.real_quantity}}</td>
      <td class=" scope price"                                >{{entry.scope_unt_price}}</td>
      <td style="display: none;" class="invoice "             >{{entry.invoice_unt_price }}</td>
      <td style="display: none;" class="planif "              >{{entry.planif_unt_price }}</td>
      <td style="display: none;" class=" target "             >{{entry.target_unt_price }}</td>
      <td style="display: none;" class=" real "               >{{entry.real_unt_price }}</td>
      <td class=" scope price"                                >{{entry.scope_price}}</td>
      <td style="display: none;" class="invoice"              >{{entry.invoice_price}}</td>
      <td style="display: none;" class="planif"               >{{entry.planif_price}}</td>
      <td style="display: none;"  class="target"              >{{entry.target_price}}</td>
      <td style="display: none;"  {% if  chapter.total_price_target <  chapter.total_price_real %}  class="real perdidas "   {%  elif   chapter.total_price_real <  chapter.total_price_target %} class="real ganacias " {%  else  %}  class= 'real'{% endif %} >{{entry.real_price}}</td>
  </tr>

      
     

  <tr  class='{{entry.id}}  entry-item'   style=" font-size: 0.9em ;display: none;" > 
    <td style="width: 95px">                                                                                 
      <button 
      id="" 
      style="" 
      class="btn btn-primary btn-xs" 
      type="submit" class="">
      <span class="glyphicon glyphicon-plus"></span>Item 
    </button>     
       
    </td>

    <th>Code</th>
    <th>Units</th> 
    <th>Breakdown of {{entry.entry_name}} </th> 
    <th class=" scope price"                                   >Quantity/Entry[scope]</th> 
    <th style="display: none;"  class="target"                 >Quantity/Entry[Target]</th> 
    <th style="display: none;"  class="real"                   >Quantity/Entry[Real]</th> 
    <th class=" scope price"                                   >Item Price[Scope]</th>
    <th style="display: none;"  class="real"                   >Item Price[Real]</th>
    <th class=" scope price"                                   >Price/Entry unit[scope]</th> 
    <th style="display: none;"  class="target"                 >Price/Entry unit[Target]</th>  
    <th style="display: none;"  class="real"                   >Price/Entry unit[Real]</th>  
      
  </tr>

    {% for it in entry.entry_item_price_set.all %}

<tr  class='{{entry.id}}  entry-item'   style=" font-size: 0.9em ;display: none;" > 

    <td style="width: 95px">                                                                                 
         
      <button id="" style="" class="btn btn-warning btn-xs" type="submit" class=""><span class="glyphicon glyphicon-pencil"></span> </button> 
      <button id="" style="" class="btn btn-danger btn-xs" type="submit" class=""><span class="glyphicon glyphicon-trash"></span> </button> 
    </td>
    <td>{{it.item.code}}</td>
    <td>{{it.item.unit}}</td>
    <td>{{it.item.item_name}}</td>
    <td class=" scope price"                        >{{it.quantity_per_entry_unit_scope  }}</td>
    <td style="display: none;"  class="target"      >{{it.quantity_per_entry_unit_target }}</td>
    <td style="display: none;"  class="real"        >{{it.quantity_per_entry_unit_real   }}</td>
    <td class=" scope price"                        >{{it.item_price_scope}}</td>
    <td style="display: none;"  class="real"        >{{it.item_price}}</td>
    <td class=" scope price"                        >{{it.price_per_entry_unit_scope }}</td>
    <td style="display: none;"  class="target"      >{{it.price_per_entry_unit_target   }}</td>
    <td style="display: none;"  class="real"        >{{it.price_per_entry_unit_real}}</td>
  
</tr>    
  
    {% endfor %}
    {% endfor %}

     </tr>
      {% empty %}
        <tr>
          <td colspan="7" class="text-center bg-warning">No Chapters</td>
        </tr>
    {% endfor %}
      
      </tbody>

      </table>
      