fernando/apps/profiles/urls.py
import re 
from django.urls import path
from  .views import  client_list,profiles_detail



app_name = 'profiles'
urlpatterns = [
   
    
    path('client_list', client_list, name='client_list'),
    path('profiles_detail/<action>/<id>', profiles_detail, name='profiles_detail'),




    ]

fernando/apps/users/urls.py
import re 
from django.urls import path
from django.contrib.auth import views as auth_views
from  .views import  (
	home , user_list, user_create,user_update,user_delete,user_filter_list,
	validate_username

		)
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
   
    path('', home, name='home'),
    path('user_list', user_list, name='user_list'),
    path('user_create', user_create, name='user_create'),
    path('user/<id>/update', user_update, name='user_update'),
    path('user/<id>/delete', user_delete, name='user_delete'),
    path('user_filter_list', user_filter_list, name='user_filter_list'),
    path('login/', auth_views.login,{'template_name':'users/login.html' }, name='login'),
    path('logout/', auth_views.logout,{'next_page': '/'}, name='logout'),
    path('ajax/validate_username/', validate_username, name='validate_username'),
    
]

fernando/fernando/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib .auth import urls as auth_urls
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('apps.users.urls')),
    path('', include('apps.profiles.urls')),
    path('', include('apps.invoices.urls')),
    path('', include('apps.projects.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
    

]



if settings.DEBUG :
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fernando/apps/users/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from apps.quotes.models import Quote
from apps.projects.models import Project







class User(AbstractBaseUser, PermissionsMixin):

    email        = models.EmailField(_('email address'), unique=True ,help_text='Introduce a valid email please')
    date_joined  = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active    = models.BooleanField(_('active'), default=True)
    is_admin     = models.BooleanField(default=False)
    is_staff     = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_client    = models.BooleanField(default=False,)
    is_visitor   = models.BooleanField(default=True,)
    is_employee  = models.BooleanField(default=False,)
    is_provider  = models.BooleanField(default=False,)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('Users')
        verbose_name_plural = _('users')


    def email_user(self, subject, message, from_email=None, **kwargs):
       
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Profile_Client(models.Model):
    company_name      = models.CharField(max_length=30, blank=True, default="Introduce company name")
    user              = models.OneToOneField(User, on_delete=models.CASCADE ,verbose_name="Email")
    physical_address  = models.CharField(max_length=200, blank=True)
    postal_address    = models.CharField(max_length=30, blank=True)
    phone             = models.CharField(max_length=30, blank=True)
    gst_registered    = models.BooleanField(default=True)
    company_director  = models.CharField(max_length=30, blank=True, default="Introduce company director")
    company_email     = models.EmailField(_('email address'),blank=True)
    
    def __str__(self):
        return    self.company_name
    

    
    

    class Meta:        
        verbose_name = "Client Profile"
        verbose_name_plural = "Client Profiles"


class Profile_Provider(models.Model):
    user              = models.OneToOneField(User, on_delete=models.CASCADE ,verbose_name="Email")
    company_name      = models.CharField(max_length=30, blank=True,default="Introduce company name")
    address           = models.CharField(max_length=200, blank=True)
    city              = models.CharField(max_length=30, blank=True)
    location          = models.CharField(max_length=30, blank=True)
    postal_Code       = models.CharField(max_length=4, blank=True)
    gst_registered    = models.BooleanField(default=True)
    company_director  = models.CharField(max_length=30, blank=True, default="Introduce company director")
    company_email     = models.EmailField(_('email address'),blank=True)
    contact_phone     = models.CharField(max_length=30, blank=True)
    contact_person1   = models.CharField(max_length=30, blank=True)
    contact_person1   = models.CharField(max_length=30, blank=True)
    contact_person2   = models.CharField(max_length=30, blank=True)


    def __str__(self):
        return   self.company_name

    class Meta:        
        verbose_name = "Provider Profile"
        verbose_name_plural = "Provider Profiles"


class Profile_Employee(models.Model):
    user              = models.OneToOneField(User, on_delete=models.CASCADE ,verbose_name="Email")
    avatar            = models.ImageField(upload_to='avatars/', null=True, blank=True)
    employee_name     = models.CharField(max_length=30, blank=True, )
    employee_email    = models.EmailField(("email"),max_length=30, blank=True, default="email")
    position          = models.CharField(max_length=30, blank=True, default="position")
    hour_price_int    = models.DecimalField(blank=True,null=True,decimal_places=2,max_digits=10)
    hour_price        = models.DecimalField(blank=True,null=True,decimal_places=2,max_digits=10)
    start_date        = models.DateField(blank=True, null=True)
    address           = models.CharField(max_length=200, blank=True)
    city              = models.CharField(max_length=30, blank=True)
    location          = models.CharField(max_length=30, blank=True)
    postal_Code       = models.CharField(max_length=4, blank=True)


    class Meta:        
        verbose_name = "Employee Profile"
        verbose_name_plural = "Employee Profiles"

    def __str__(self):
        return self.employee_name







@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    try:

        if instance.is_client: 
            if created:
                a=instance.email
                Profile_Client.objects.create(user=instance,company_email=a)
                
        elif instance.is_employee:
            if created:
                a=instance.email
                Profile_Employee.objects.create(user=instance,employee_email=a)

        elif instance.is_provider:
            if created:
                a=instance.email
                Profile_Provider.objects.create(user=instance,company_email=a)
        else:

            pass
    except :
        pass


@receiver(post_save, sender=User)
def save_user_profile(sender, instance,**kwargs):
    
    try:
        a=instance.email
        if instance.is_client:
            instance.profile_client.save()
            
    except :
        if instance.is_client:
            Profile_Client.objects.create(user=instance,company_email=a )

    try:
        a=instance.email
        if instance.is_employee:

            instance.profile_employee.save()
    except :
        if instance.is_employee:
            Profile_Employee.objects.create(user=instance,employee_email=a)  

    try:
        a=instance.email
        if instance.is_provider:
            instance.profile_provider.save()
    except :
        if instance.is_provider:
            Profile_Provider.objects.create(user=instance,company_email=a)    



    try:   
        if not instance.is_provider:
            instance.profile_provider.delete()
            
    except:
        pass

    try:   
        if not instance.is_employee:
            instance.profile_employee.delete()
            
    except:
        pass

    try:   
        if not instance.is_client:
            
            instance.profile_client.delete()
    except:
        pass

fernando/apps/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User, Profile_Client, Profile_Employee, Profile_Provider
from django import forms

class UserCreationForm(UserCreationForm):

	CLIENT = 1
	EMPLOYEE = 2
	PROVIDER = 3
	ADMIN = 4
	VISITOR = 5
	USER_TYPES = (
		(CLIENT, 'Client'),
        (EMPLOYEE, 'Employee'),
        (PROVIDER, 'Provider'),
        (ADMIN,'Admin'),
        (VISITOR,'Visitor')
        )

	user_type = forms.ChoiceField(choices = USER_TYPES, label=" User Type", initial='', widget=forms.Select(), required=True)
	

	class Meta:
		model = User
		fields = ('email','is_active',)

fernando/apps/users/views.py
from django.shortcuts import render
from .models import  User
from django.http import JsonResponse
from django.template.loader import render_to_string
from .forms import UserCreationForm
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .decorators import superuser,is_client
from django.contrib.auth.decorators import login_required


def home(request):
    context = {}
    return render(request, "users/home.html" , context)

@superuser
def user_list(request):
    action=""
    user = User.objects.all()
    query = request.GET.get('q', "")
    if query:
        user=user.filter(
            email__icontains=query)
    paginator = Paginator(user, 10)
    page = request.GET.get('page', 1)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'users/client_list.html', {'users': users, 'action':action})


@superuser
def save_user_form(request, form, template_name, action,id):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            user_type=form.cleaned_data['user_type']
            email=form.cleaned_data['email']

            form.save()
            if user_type=='1':
                user=User.objects.get(email=email)
                user.is_client=True
                user.is_visitor=False
                user.is_employee=False
                user.is_provider=False
                user.save()
            if user_type=='2':
                user=User.objects.get(email=email)
                user.is_employee=True
                user.is_visitor=False
                user.is_provider=False
                user.is_client=False
                user.save()
            if user_type=='3':
                user=User.objects.get(email=email)
                user.is_provider=True
                user.is_visitor=False
                user.is_client=False
                user.is_employee=False
                user.save()
            if user_type=='4':
                user=User.objects.get(email=email)
                user.is_superuser=True
                user.is_visitor=False
                user.is_client=False
                user.is_employee=False
                user.is_provider=True
                user.save()
            data['form_is_valid'] = True
            if action == 'create':
                users = User.objects.all().order_by('id').reverse()[:1]
                data['action']='create'
                data['html_user_list'] = render_to_string('users/partial_user_list.html', {
                    'users': users})

            if action == 'update':
                user = User.objects.filter(email=email)
                data['action']='update'
                data['html_user_list'] = render_to_string('users/partial_user_list.html', {'users': user})
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@superuser				
def user_create(request):
	
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		
	else:
		form = UserCreationForm()
	
	return save_user_form(request, form, 'users/partial_user_create.html','create',id)


@superuser
def user_update(request, id):
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        form = UserCreationForm(request.POST, instance=user)
    else:
        form = UserCreationForm(instance=user)
    return save_user_form(request, form, 'users/partial_user_update.html','update' ,id)


@superuser
def user_delete(request, id):
    user = get_object_or_404(User, id=id)
    data = dict()
    if request.method == 'POST':
        user.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        users1 = User.objects.all()
        data['action']='delete'
        data['html_user_list'] = render_to_string('users/partial_user_list.html', {
            'users': users1
        })
    else:
        context = {'user': user}
        data['html_form'] = render_to_string('users/partial_user_delete.html',

            context,
            request=request,
        )
    return JsonResponse(data)


@superuser
def user_filter_list(request):

    data = dict()
    users = User.objects.all()
    query = request.GET.get('q', "")
    if query:
        users =users.filter(email__icontains=query)

    data['html'] = render_to_string('users/partial_user_list.html', 
            {'users': users}, request=request)
    return JsonResponse(data)


def validate_username(request,*args,**kwargs):
    email = request.GET.get('email', None)
    data = {
        'is_taken': User.objects.filter(email__iexact=email).exists()
    }
    return JsonResponse(data)


    
    

fernando/apps/users/templates/users/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="{% static 'css/bootstrap-3.3.7.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
{% block style %}
{% endblock %}


  <body style="">
    
  
    <div class="container" style="width: 95%" >
      {% block content %}
      {% endblock %}
    <div>

    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>  
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/pepe.js' %}"></script>
    <script src="{% static 'js/project.js' %}"></script>
    <script src="{% static 'js/meassurement.js' %}"></script>
    <script src="{% static 'js/tablesorter.js' %}"></script> 
    {% block javascript %}
    {% endblock %}
  </body>
</html>

fernando/apps/users/templates/users/client_list.html
{% extends 'users/base1.html' %}
{% load static %}

{% block javascript %}
  <script src="{% static 'js/users.js' %}"></script>
 
{% endblock %}



{% block style %}
 <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">

{% endblock %}



{% block content %}
  
<div class="container" style="background: white; ">

  <h1 class="page-header">USERS</h1>


<p>
    <button style="float: left;" type="button" class="btn btn-primary js-create" data-url="{% url 'users:user_create' %}"  >
      <span class="glyphicon glyphicon-plus"></span>
      New user
    </button>
    <form class="" role="search">
        
          <input style="float: left; width: 200px; margin-left: 40px" name="q"  type="search" class="form-control"  id="buscador" placeholder="Search">
       
        <button style="margin-left: 20px"  type="submit"  class="btn btn-success">Submit</button>
      </form>
  </p>


  <table class="table table-hover" id="book-table">
    <thead>
      <tr>
        <th>ID</th>
        <th>EMAIL</th>
        <th>DATE JOINED</th>
         <th>ACTIVE</th>
        <th>CATEGORY</th>
        </tr>
    </thead>
    <tbody>
      <div class="container-fluid" style="width: 97%" >
      {% include 'users/partial_user_list.html' %}
      <div>
  </table>

  <div class="modal fade" id="modal-book">
    <div class="modal-dialog  ">


      <div class="modal-content">
      </div>
    </div>
  </div>
  {% if users.has_other_pages %}
  <ul class="pagination">
    {% if users.has_previous %}
      <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in users.paginator.page_range %}
      {% if users.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
      <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

fernando/apps/users/templates/users/home.html
{% extends "base.html" %}

{% block title %} {% endblock %} 


{% block style %}

<style type="text/css">
	
</style>
{% endblock %}

{% block script %}
{% endblock %}




{% block content %}
<div >
<h2 style="color: red; ">  Landing page  </h2>
</div>
{% endblock %}

fernando/apps/users/templates/users/login.html
{% extends "users/base1.html" %}
{% load widget_tweaks %}

{% block style %}

<style type="text/css">
  
#main{
  margin-top: 100px;
  width: 40%;
  margin: auto ;
  margin-top: 100px;
  border: solid 1px ;
  padding: 30px;
  border-radius: 5px;
  background:  rgba(226,226,226,1.00);
}




</style>

{% endblock %}


{% block content %}

<div  id="main">
<form method="post" novalidate>
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">Submit</button><br><br>
  <a style=" color: red" href="http://127.0.0.1:8000/accounts/password_reset">Forgot password ?</a>
</form>

</div>


{% endblock %}

fernando/apps/users/templates/users/partial_user_create.html
{% load static %}


 
<form method="post" action="{% url 'users:user_create' %}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new user</h4>
  </div>
  <div class="modal-body">
    {% include 'users/partial_user_form.html' %}
    
    
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button id="pepe1" type="submit" class="btn btn-primary">Create User</button>
  </div>
</form>

fernando/apps/users/templates/users/partial_user_delete.html
<form method="post" action="{% url 'users:user_delete' user.id %}" class="js-book-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm book deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the book <strong>{{ user.email }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete user</button>
  </div>
</form>

fernando/apps/users/templates/users/partial_user_form.html
{% load static %}
{% load widget_tweaks %}

 <script src="{% static 'js/users1.js' %}"></script>


{% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
{% endfor %}
  </div>
{% endfor %}

fernando/apps/users/templates/users/partial_user_list.html
{% load static %}







{% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
           {%  if user.is_client %}
          <td><a   class="btn" href="{% url 'profiles:profiles_detail'   action='Profile_Client'   id=user.profile_client.id %}">{{ user.email  }}</a></td>
          {%elif user.is_employee%}

          <td><a   class="btn" href="">{{ user.email  }}</a></td>

          {%elif user.is_provider%}

          <td><a   class="btn" href="">{{ user.email  }}</a></td>
          {%elif user.is_superuser%}

          <td><a   class="btn" href="">{{ user.email  }}</a></td>



           {% endif %}
          
          
          
          <td>{{ user.date_joined }}</td>
          <td>{{ user.is_active}}</td>

          {% if user.is_superuser  %}
           <td>Administrador</td>

           {% elif user.is_client %}
           <td>client</td>
           {% elif user.is_employee %}
           <td>Employee</td>
           {% elif user.is_provider %}
           <td>Provider</td>
           {% elif user.is_visitor %}
           <td>Visitor</td>

           {% endif  %}

           <td>
      <button type="button"
              class="btn btn-warning btn-sm js-update-book"
              data-url="{% url 'users:user_update' user.id %}">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-book"
              data-url="{% url 'users:user_delete' user.id %}">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </td>
          
        </tr>
      {% empty %}
        <tr>
          <td colspan="7" class="text-center bg-warning">No users</td>
        </tr>
      {% endfor %}

fernando/apps/users/templates/users/partial_user_update.html
<form method="post" action="{% url 'users:user_update' form.instance.id %}" class="js-book-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update User</h4>
  </div>
  <div class="modal-body">
    {% include 'users/partial_user_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update user</button>
  </div>
</form>