fernando/apps/projects/urls.py
import re 
from django.urls import path
from  .views import  (project_list,project_detail,
					 project_create,
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c91cb4386d590368f205d60686c8801180347e3f

					 scope_detail,chapter_create,chapter_delete,
					 chapter_update,

					 scope_detail,chapter_create,chapter_delete,chapter_update
=======
					 scope_detail,chapter_create,chapter_delete,chapter_update,
                      meassurement_scope,meassurement_create,
                      meassurement_delete,entry_item_create
                      
                      
                     
>>>>>>> fernando



)

app_name = 'projects'
urlpatterns = [
   
    path('project_list', project_list, name='project_list'),
    path('project_detail/<id>/', project_detail, name='project_detail'),
    path('project_create/<id>/', project_create, name='project_create'),
    path('scope_detail/<id>', scope_detail, name='scope_detail'),
    path('chapter_create/<id>', chapter_create, name='chapter_create'),
    path('chapter_delete/<id>', chapter_delete, name='chapter_delete'),
    path('chapter_update/<id>', chapter_update, name='chapter_update'),
    path('meassurement_scope/<id>',  meassurement_scope, name= 'meassurement_scope'),
    path('meassurement_create/<id>',  meassurement_create, name= 'meassurement_create'),
    path('meassurement_delete/<id_meassurement>/<id_entry>',  meassurement_delete, name= 'meassurement_delete'),
    path('entry_item_create/<id_entry>',  entry_item_create, name= 'entry_item_create'),
   
    
    
]

fernando/fernando/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib .auth import urls as auth_urls
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('apps.users.urls')),
    path('', include('apps.profiles.urls')),
    path('', include('apps.invoices.urls')),
    path('', include('apps.projects.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
    

]



if settings.DEBUG :
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fernando/apps/projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from fernando import settings



class Project_Creation_Form(ModelForm):


	
	class Meta:
		model = Project
		fields = '__all__'



class Entry_Creation_Form(ModelForm):

	class Meta:
		model = Entry
		fields = '__all__'


class Chapter_Creation_Form(ModelForm):

	class Meta:
		model = Chapter
		fields = ('code','units','chapter_name','quantity_scope','quantity_invoice','quantity_planif','quantity_target','quantity_real')

class Meassurement_Creation_Form(ModelForm):

	class Meta:
		model =  Scope_Meassurement
		exclude = ('entry ','total_meassurement', 'indirect_cost_entry',)


class Entry_Item_Price_Form (ModelForm) :

	model  =  Entry_Item_Price
	fields =  ('item', 'quantity_per_entry_unit_scope', 'item_price',)

fernando/apps/projects/views.py
from django.shortcuts import render
from .models import *
from .forms import  Project_Creation_Form,Chapter_Creation_Form, Meassurement_Creation_Form
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from apps.users.decorators import superuser,is_client
from django.contrib.auth.decorators import login_required
from apps.users.models import User, Profile_Employee
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.http import JsonResponse

@superuser
def project_list(request, **kwargs):
	user    = Project.objects.all().order_by('-date')
	template = 'projects/project_list.html'
	query = request.GET.get('q', "")
	if query:
		user=user.filter(
        	Q(project_name__icontains=query)|
        	Q(client__icontains=query)|
        	q(project_manager__icontains=query)
            )
	paginator = Paginator(user, 10)
	page = request.GET.get('page', 1)
	try:
		users = paginator.page(page)
	except PageNotAnInteger:
		users = paginator.page(1)
	except EmptyPage:
		users = paginator.page(paginator.num_pages)
	return render(request, template, {'projects': users})


@superuser
def project_detail(request,**kwargs):
	template = 'projects/project_detail.html'
	obj = get_object_or_404(Project, id=kwargs['id'])
	context = {'obj':obj}
	return render( request, template, context)


def project_create(request, **kwargs):
	template= 'projects/project_create.html'

	obj = get_object_or_404(Project, id=kwargs['id'])
	if request.method == 'POST':
		form = Project_Creation_Form(request.POST, instance=obj )
		if form.is_valid():
			it=form.save(commit =False)

			project_manager     =form.cleaned_data['project_manager']
			
			site_manager        =form.cleaned_data['site_manager']
			quantity_surveyor   =form.cleaned_data['quantity_surveyor']
			foreman             =form.cleaned_data['foreman']
			client              = form.cleaned_data['client']
			it.save()
			fo =it.foreman.all()
			sm = it.site_manager.all()
			qs = it.quantity_surveyor.all()
			pm = it.project_manager.all()
			if site_manager:	
				for obj in site_manager:
					if obj in sm:
						pass
					else:
						it.site_manager.add(obj)
			elif  not site_manager:
				for obj in sm:
					it.site_manager.remove(obj)

			for obj in sm:
				if obj in site_manager:
					pass
				else:
					it.site_manager.remove(obj)
			else:
				pass
			

			if quantity_surveyor:	
				for obj in quantity_surveyor:
					if obj in qs :
						pass
					else:
						it.quantity_surveyor.add(obj)
			elif  not foreman:
				for obj in fo:
					it.foreman.remove(obj)

			for obj in qs:
				if obj in quantity_surveyor:
					pass
				else:
					it.quantity_surveyor.remove(obj)
			else:
				pass

			if foreman:	
				for obj in foreman:
					if obj in fo :
						pass
					else:
						it.foreman.add(obj)
			elif  not foreman:
				for obj in fo:
					it.foreman.remove(obj)

			for obj in fo:
				if obj in foreman:
					pass
				else:
					it.foreman.remove(obj)
			else:
				pass


			if project_manager:	
				for obj in project_manager:
					if obj in pm :
						pass
					else:
						it.project_manager.add(obj)
			elif  not project_manager:
				for obj in pm:
					it.project_manager.remove(obj)

			for obj in pm :
				if obj in project_manager:
					pass
				else:
					it.project_manager.remove(obj)
			else:
				pass	
		return redirect ('projects:project_create' ,id=kwargs['id'])
	else:
		
		form=Project_Creation_Form(instance=obj)
		context = {'form':form ,'obj':obj}

		return render(request, template, context)


@superuser
def scope_detail(request,**kwargs):

	template   = 'projects/scope.html'


	project     = get_object_or_404(Project, id=kwargs['id'])
	scope       = Scope.objects.get(project=project)
	chapters    = Chapter.objects.filter(scope=scope)
	user        = get_object_or_404(User , email=request.user.email)

	context={
				
				'project':project,
				'scope':scope,
				'chapters':chapters,
				'user':user
			
	}

	return render(request,template, context )

def save_chapter_form(request, form, template_name, id):
    data = dict()
   
    if request.method == 'POST':
        if form.is_valid():
          	form.save()
          	scope       = get_object_or_404(Scope , id=id)
          	chapters    = Chapter.objects,filter(scope=scope)
          	project     = scope.project
          	user        = get_object_or_404(User , email=request.user.email)
          	context={'project':project,'scope':scope,'chapters':chapters,'user':user}
          	data['form_is_valid'] = True
          	data['html_scope'] = render_to_string('projects/scope_partial.html', context)
        else:
            data['form_is_valid'] = False
    context = {'form': form , 'id':id}
    print(id)
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@superuser				
def chapter_create(request ,**kwargs):

	scope_id = kwargs['id']
	scope = get_object_or_404(Scope , id=scope_id)
	initial =scope

	id=kwargs['id']
	scope = get_object_or_404(Scope , id=id)
	

	print (scope)
	if request.method == 'POST':
		form = Chapter_Creation_Form(request.POST)
		
	else:
		form = Chapter_Creation_Form()
	return save_chapter_form(request, form, 'projects/chapters/partial_chapter_create.html',id)

@superuser
def chapter_update(request, id):

   


	data=dict()
	chapter = get_object_or_404(Chapter, id=id)
	scope       = Scope.objects.get(chapter=chapter)
	user        = get_object_or_404(User , email=request.user.email)
	project     = scope.project
	chapters    = Chapter.objects.filter(scope=scope)
	context={
        		'project':project,
				'scope':scope,
				'chapters':chapters,
				'user':user
				}
	if request.method == 'POST':
		form = Chapter_Creation_Form(request.POST, instance=chapter)
		if form.is_valid():
			chapter.save()
			data['form_is_valid'] = True  # This is just to play along with the existing code
			data['html_scope'] = render_to_string('projects/scope_partial.html', context)

		else:
			data['form_is_valid'] = False
	form = Chapter_Creation_Form(instance=chapter)
	data['html_form'] = render_to_string('projects/chapters/partial_chapter_update.html', {'form':form} , request=request)
	return JsonResponse(data)


@superuser
def chapter_delete(request, id):
    
    data = dict()
   
    chapter     = get_object_or_404(Chapter ,id=id)
    scope       = Scope.objects.get(chapter=chapter)
    user        = get_object_or_404(User , email=request.user.email)
    project     = scope.project
    chapters    = Chapter.objects.filter(scope=scope)
    context={
				'chapters':chapters,
				'project':project,
				'scope':scope,
				'user':user
			
	}
    if request.method == 'POST':
        chapter.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        data['action']='delete'
        data['html_scope'] = render_to_string('projects/scope_partial.html', context)
    else:
        context = {'chapter':chapter}
        data['html_form'] = render_to_string('projects/chapters/partial_chapter_delete.html', context, request=request,)
    return JsonResponse(data)

####MEASSUREMENTS
#####################################################


@superuser
def meassurement_scope(request , **kwargs):

	template = 'projects/meassurements/meassurement_list.html'
	id_entry =kwargs['id']
	entry = get_object_or_404(Entry, id=id_entry)
	meassurement_list =  Scope_Meassurement.objects.filter(entry=entry).order_by('id')
	context ={
			'entry':entry,
			"meassurement_list":meassurement_list
	}
	return render (request , template, context)


#crear mediciones ajax
@superuser			
def meassurement_create(request ,**kwargs):
	data=dict()
	id_entry =kwargs['id']
	entry       = get_object_or_404(Entry, id=id_entry)
	meassurements =Scope_Meassurement.objects.filter(entry=entry)
	context={
        		'entry':entry,
				'meassurement_list':meassurements
				}
	if request.method == 'POST':
		form = Meassurement_Creation_Form(request.POST)
		
		if form.is_valid():

			obj=form.save(commit=False)
			if obj.quantity == None and obj.coments == None:
				data['form_is_valid'] = True
				meassurement_list = Scope_Meassurement.objects.filter(entry=entry)
				data['html_meassurements'] = render_to_string('projects/meassurements/partial_meassurements.html',
																{'meassurement_list':meassurement_list,
																'entry':entry })
			else:
				obj.entry=entry
				obj.save()
				meassurement_list = Scope_Meassurement.objects.filter(entry=entry)

				data['form_is_valid'] = True  # This is just to play along with the existing code
				data['html_meassurements'] = render_to_string('projects/meassurements/partial_meassurements.html',
																{'meassurement_list':meassurement_list,
																'entry':entry })

		else:
			data['form_is_valid'] = False
	form = Meassurement_Creation_Form()
	data['html_form'] = render_to_string('projects/meassurements/meassurement_scope_form.html',
										 {'form':form ,'entry':entry} , 
										 request=request)
	return JsonResponse(data)

@superuser
def meassurement_delete(request ,**kwargs):

	data = dict()
	id_meassurement   = kwargs['id_meassurement']
	id_entry          = kwargs['id_entry']
	entry             = get_object_or_404(Entry, id=id_entry)
	meassurement      = get_object_or_404(Scope_Meassurement, id=id_meassurement)
	meassurements     = Scope_Meassurement.objects.filter(entry=entry)
	
	if request.method == 'GET':
		meassurement.delete()
		

		meassurement_list = Scope_Meassurement.objects.filter(entry=entry)
	
		data['html_meassurements'] = render_to_string('projects/meassurements/partial_meassurements.html',
														{'meassurement_list' : meassurement_list,
														'entry':entry },
														request=request)
	if  request.method == 'POST':
		meassurement.delete()
		meassurement_list = Scope_Meassurement.objects.filter(entry=entry)
	

fernando/apps/projects/templates/projects/chapters/partial_chapter_create.html
{% load static %}


 
<form method="post" action="{% url 'projects:chapter_create' id=scope.id %}" class="js-chapter-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new Chapter</h4>
  </div>
  <div class="modal-body">
    {% include 'projects/chapters/partial_chapter_form.html' %}
    
    
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button id="pepe1" type="submit" class="btn btn-primary">Create Chapter</button>
  </div>
</form>

fernando/apps/projects/templates/projects/chapters/partial_chapter_delete.html
<form method="post" action="{% url 'projects:chapter_delete' chapter.id %}" class="js-chapter-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm Chapter deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete Chapter <strong>{{ chapter.chapter_name}}</strong>? 

      you will loose all the entries, meassurements ,and financial documents asociated to this chapter


    </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Chapter</button>
  </div>
</form>

fernando/apps/projects/templates/projects/chapters/partial_chapter_form.html
 
{% load static %}


 <table style="text-align: center;"  border="0"  class="table table-bordered ">
  <tbody>
    <tr  style="background:#B39609" >

      <th scope="col" style="width: 30px"                                 >Code</th>
      <th scope="col" style="width: 30px"                                 >Unit</th>
      <th style="" scope="col"                                            >Chapter</th>
      <th class="scope" scope="col"                                       >Quantity[scope]</th>
      <th style=""  class="real" scope="col"                              >quantity[Real]</th>
      
 



<tr  style="background:#AAC7A0">
      <td  style="width: 50px"                                             >{{form.code}}</td>
      <td  style="width: 50px"                                             >{{form.units}}</td>
      <td id="{{chapter.id}}" style="width: 100%; font-weight: bold; "     >{{form.chapter_name}}</td>
      <td style=""  class="scope          "                                >{{form.quantity_scope}}</td>
      <td style=""  class="real"                                           >{{form.quantity_real}}</td>

</tr>




</tbody>

</table>

     
   

fernando/apps/projects/templates/projects/chapters/partial_chapter_update.html
<<<<<<< HEAD
<form method="post" action="{% url 'projects:chapter_update' id=chapter.id %}" class="js-chapter-update-form">
=======
<form method="post" action="{% url 'projects:chapter_update' form.instance.id %}" class="js-chapter-update-form">
>>>>>>> adec64c
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update Chapter</h4>
  </div>
  <div class="modal-body">
    {% include 'projects/chapters/partial_chapter_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update Chapter</button>
  </div>
</form>